name: Address Sanitizer

env:
    DEBUG: 'napi:*'

on:
    push:
    pull_request:

jobs:
    build_and_test:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3

            - name: Setup java 17
              run: |
                wget https://www.dropbox.com/s/chrfc3fr864y6be/jdk.zip?dl=1
                unzip jdk.zip
                echo "JAVA_HOME=$(pwd)/jdk" >> $GITHUB_ENV

            - name: Install
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  profile: minimal
                  components: rust-src
                  override: true

            - name: Rust Cache
              uses: Swatinem/rust-cache@v2.2.1

            - name: Cargo tests with address sanitizer
              run: cargo test --all-features -Zbuild-std --target=x86_64-unknown-linux-gnu
              env:
                  RUST_TARGET: x86_64-unknown-linux-gnu
                  RUST_BACKTRACE: 1
                  RUSTFLAGS: -Zsanitizer=address
                  #ASAN_OPTIONS: detect_leaks=0
                  RUSTDOCFLAGS: -Zsanitizer=address
                  #LD_PRELOAD: /usr/lib/gcc/x86_64-linux-gnu/9/libasan.so

            - name: Clear the cargo caches
              run: |
                  cargo install cargo-cache --no-default-features --features ci-autoclean
                  cargo-cache
