name: Address Sanitizer

on:
    push:

jobs:
    test-with-asan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: addnab/docker-run-action@v3
              with:
                registry: gcr.io
                image: markusjx/prebuilt-debug-jdk:17-bullseye
                options: -v ${{ github.workspace }}:/app
                run: |
                  cargo update
                  cargo test --all-features -Zbuild-std --target=x86_64-unknown-linux-gnu
