name: Address Sanitizer

env:
    DEBUG: 'napi:*'

on:
    push:
    pull_request:

jobs:
    build_and_test:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v3

            - name: Setup java 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Install
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  profile: minimal
                  components: rust-src
                  override: true

            - name: Rust Cache
              uses: Swatinem/rust-cache@v2.2.1

            - name: Cargo tests with address sanitizer
              run: |
                  LD_PRELOAD=/usr/lib/gcc/x86_64-linux-gnu/9/libasan.so cargo test --verbose --all-features
              env:
                  RUST_TARGET: x86_64-unknown-linux-gnu
                  RUST_BACKTRACE: 1
                  RUSTFLAGS: -Z sanitizer=address
                  ASAN_OPTIONS: detect_leaks=0

            - name: Clear the cargo caches
              run: |
                  cargo install cargo-cache --no-default-features --features ci-autoclean
                  cargo-cache
